config/routes.rb
Rails.application.routes.draw do
  namespace :api, { format: 'json' } do
    namespace :v1 do # バージョン1を表している
      resources :items_api
      resources :stocks_api
      resources :ships_api
    end
  end
  devise_for :users
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end
  
  root to: 'stocks#index'
  resources 'items'
  resources 'stocks', only: [:new, :create, :show, :destroy]
  resources 'ships', only: [:new, :create, :index, :show, :destroy]

  delete 'items', to: 'items#destroy_many'
  post 'items/select', to: 'items#category_select'
  post 'items/quantity', to: 'items#item_quantity'
  post 'items/search', to: 'items#search_item'
  # if Rails.env.development?
  #   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # end
 
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :item
  validates :quantity, presence: true, numericality: {only_integer: true, greater_than: 0}

  

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authenticate_user!, only: :show
  def new
    @items = Item.all
    @stock = Stock.new
  end

  def create
    @stock = Stock.new(stock_param)
    if @stock.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @stocks = Stock.where(item_id: params[:id])
    @item = Item.find(params[:id])
  end

  def destroy
    @stock = Stock.find(params[:id])
    @item = Item.find_by(id: @stock.item_id)
    @stock.destroy
    @stocks = Stock.where(item_id: @stock.item_id)
    redirect_to items_path
  end


  private

  def stock_param
    params.require(:stock).permit(:quantity, :item_id)
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/index.html.erb
<div class="top-main" id="top-main">
  <%= render partial: 'layouts/pulldown'%>
  <% if user_signed_in? %>
    <%= render partial: 'layouts/sidebar'%>
  <%else%>
    <div class= "blank_side_bar">
    </div>
  <%end%>
  <div class="toppage_content">
    <div class="buttons">
      <div class="top_btn">
        <%=link_to "入庫", new_stock_path, class: "stock_top_btn" %>
      </div>
      <div class="top_btn">
        <%=link_to "出庫", new_ship_path, class: "ship_top_btn"%>
      </div>
    </div>
  </div>
</div>

app/views/stocks/new.html.erb
<div class="stock_main">
  <%= render partial: 'layouts/pulldown'%>
  
  <div class="stock_main_sub">
    <div class="stock_sub_title">
      備品入庫
    </div>
    
    <div class="stock_form">
    <%= form_with(model: @stock, local: true, id:"stock-form", class: "stock_form_contents") do |f|%>
      <div class="stock_error">
        <%= render 'layouts/error_messages', model: f.object %>
      </div>
      <div class="form-example">
        <%= f.label :"カテゴリー", class: "stock_form_label"  %>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"stock_form_content", id:"stock-category-select"})%>
      </div>
      <div class="form-example">
        <%= f.label :"備品名", class: "stock_form_label", id: 'stock-form-label' %>
        <%= f.collection_select(:item_id, Item.all, :id, :name, {include_blank: true}, {class:"stock_form_content", id:"stock-item-select"})%>
      </div>
      <div class="current_item_quantity" id="current-item-quantity">
      </div>

      <div class="form-example">
        <%= f.label :"入庫数", class: "stock_form_label"  %>
        <%= f.number_field :quantity, class:"stock_form_content" %><span></span>
      </div>
      <div class="stock_form_submit_area">
        <%= f.submit "入庫", class: "stock_form_submit", data: { confirm: '入庫を確定しますか？'}%>
      
      </div>
    
    <%end%>
    </div>
  </div>
</div>

app/views/stocks/show.html.erb
<div class="item-main">
  <%= render partial: 'layouts/pulldown'%>
  <%= render partial: 'layouts/sidebar'%>
  <div class="items_show">
    <div class="items_history_title">
      <div class="items_history_title_left">
        <div class="history_item_name"><%= @item.name %></div>
        <div class="history_title">
            入庫履歴
        </div>
      </div>
      <div class="history_item_button">
       
        <div class="history_on" >
          <%= link_to "出庫履歴", ship_path(@item.id), class:"history_button" %>
        </div>
        
      </div>
    </div>
    <table id="items-table" class="items_table">
      <tbody id="items-tbody">
        <tr id="menu-items-index" class="menu_items_index">  
          <th class="item_table_category">日付</th>
          <th class="item_table_name">数量</th>
          <th></th>
        </tr>
          
          <% @stocks.each do |stock|%>
              <tr id="data-items-index" class="data_items_index">
                <td class="item_table_time"><%=stock.created_at.strftime("%Y年%m月%d日")%><br><%=stock.created_at.strftime("%H時%M分")%></td>
                <td class="item_table_order_point"><%=stock.quantity%></td>
                <td class="item_table_button">
                  <%= link_to "削除", stock_path(stock), method: :delete, class:"index_button" %>
                </td>
              </tr>
           
          <%end%>
      </tbody>
    </table>
   
   
  </div>
</div>