config/routes.rb
Rails.application.routes.draw do
  namespace :api, { format: 'json' } do
    namespace :v1 do # バージョン1を表している
      resources :items_api
      resources :stocks_api
      resources :ships_api
    end
  end
  devise_for :users
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end
  
  root to: 'stocks#index'
  resources 'items'
  resources 'stocks', only: [:new, :create, :show, :destroy]
  resources 'ships', only: [:new, :create, :index, :show, :destroy]

  delete 'items', to: 'items#destroy_many'
  post 'items/select', to: 'items#category_select'
  post 'items/quantity', to: 'items#item_quantity'
  post 'items/search', to: 'items#search_item'
  # if Rails.env.development?
  #   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # end
 
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :stocks, dependent: :destroy
  has_many :ships, dependent: :destroy

  belongs_to :category
  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :quantity
    validates :order_point
  end
  validates :category_id, numericality: { other_than: 1, message: 'を選択してください' }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: :category_select
  before_action :item_find, only: [:show, :edit, :update, :destroy]


  def index
    @items = Item.all.order(id: 'DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_param)
    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def show
    @ships = Ship.where(item_id: params[:id])
    @stock = Stock.where(item_id: params[:id])
    @quantity = (@item.quantity + @stock.sum(:quantity)) - @ships.sum(:quantity)
  end

  def edit
  end

  def update
    if @item.update(item_param)
      redirect_to items
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  def destroy_many
    if params.key?('deletes')
      checked_data = params[:deletes].keys
      if Item.destroy(checked_data)
        redirect_to items_path, notice: '削除しました'
        nil
      else
        render items_path
      end
    else
      redirect_to items_path, notice: '削除する備品を選択してください'
      nil
    end
  end

  def category_select
    if category_param[:category_id] == '1'
      selected_category_items = Item.all
      render json: { selected_category_items: selected_category_items }
    else
      selected_category_items = Item.where(category_id: category_param[:category_id])
      unless selected_category_items == []
        select_item_quantity = selected_category_items[0].quantity + Stock.where(item_id: selected_category_items[0].id).sum(:quantity) - Ship.where(item_id: selected_category_items[0].id).sum(:quantity)
        quantity = {}
        quantity.store('quantity', select_item_quantity)

        render json: { selected_category_items: selected_category_items, quantity: quantity }
      else
        render json: { selected_category_items: selected_category_items }
      end
    end
  end

  def item_quantity
    select_item = Item.find_by(id: select_item_param[:item_id])
    select_item_quantity = select_item.quantity + Stock.where(item_id: select_item_param[:item_id]).sum(:quantity) - Ship.where(item_id: select_item_param[:item_id]).sum(:quantity)
    quantity = {}
    quantity.store('quantity', select_item_quantity)
    render json: { select_item: select_item, quantity: quantity }
  end

  def search_item
    search_category_items = Item.where(category_id: params[:category_id])
    category = Category.find(params[:category_id]).name

    quantity = []
    search_category_items.each do |item|
      select_item_quantity = item.quantity + Stock.where(item_id: item.id).sum(:quantity) - Ship.where(item_id: item.id).sum(:quantity)
      quantity.push(select_item_quantity)
    end
    render json: { search_category_items: search_category_items, quantity: quantity, category: category }
  end

  private

  def item_param
    params.require(:item).permit(:name, :category_id, :quantity, :order_point, :unit, :location, :store, :remarks, :image)
  end

  def item_find
    @item = Item.find(params[:id])
  end

  def delete_param
  end

  def category_param
    if params.key?('stock')
      params.require(:stock).permit(:category_id)
    elsif params.key?('ship')
      params.require(:ship).permit(:category_id)
    end
  end

  def select_item_param
    if params.key?('stock')
      params.require(:stock).permit(:item_id)
    elsif params.key?('ship')
      params.require(:ship).permit(:item_id)
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="item_new_main">
  <%= render partial: 'layouts/pulldown'%>
  <%= render partial: 'layouts/sidebar'%>

  <div class="item_new_sub">
    <div class="item_new_sub_sub">
      <div class="item_new_subtitle">
        備品情報編集
      </div>
      <%= form_with(model: @item, local: true,  class:"item_new_form_area") do |f|%>
      <div class="item_new_form">
        <div class="item_new_separate">
          <%= render 'layouts/error_messages', model: f.object %>
         
          <div class="form-example">
            <%= f.label :"備品名称", class: "form_label"  %><span class="mandatory">（必須）</span><br />
            <%= f.text_field :name, placeholder: "例：ハサミ", class:"form_text"%>
          </div>
          <div class="form-example">
            <%= f.label :"カテゴリー", class: "form_label"  %><span class="mandatory">（必須）</span><br />
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"form_text"})%>
          </div>
          <div class="form-example">
            <%= f.label :"発注点", class: "form_label"  %><span class="mandatory">（必須）</span>
            <br />
            <%= f.text_field :order_point, placeholder: "例：10（半角数字）", class:"form_text"%>
          </div>
          <div class="form-example">
            <%= f.label :"単位", class: "form_label"  %><br />
            <%= f.text_field :unit, placeholder: "例：個、袋、etc", class:"form_text"%>
          </div>
        </div>
        <div class="item_new_separate">

          
          <div class="form-example">
            <%= f.label :"保管場所", class: "form_label"  %><br />
            <%= f.text_field :location, placeholder: "例：棚A", class:"form_text"%>
          </div>
          <div class="form-example">
            <%= f.label :"発注元", class: "form_label"  %><br />
            <%= f.text_field :store, placeholder: "例：○○社", class:"form_text"%>
          </div>
          <div class="form-example">
            <%= f.label :"備考", class: "form_label"  %><br />
            <%= f.text_area :remarks, placeholder: "例：よく切れるので注意", class:"form_text"%>
          </div>
          <div class="image_selectbox">
            <div id="file-name" class="file_name">未選択</div>
            <label for="image">
              <span class="button">画像を選択</span><%= f.file_field :image, id: "image" %>
            </label>
          </div>
        </div>
      </div>
      <div class="item_new_submit_area">
        <%= f.submit value: "編集", class: "item_new_submit"%>
      </div>
      
      <%end%>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="item-main">
  <%= render partial: 'layouts/pulldown'%>
  <%= render partial: 'layouts/sidebar'%>
  <div class="items_show">
    
    <div class="search_items">
      <div class="search_items_title">
      <%= form_with(model: @item, local: true, class:"item_search_form_area", id: "item-search-form") do |f|%>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"form_text", id: "search_category"})%>
      <%end%>
      </div>

    </div>
    <div class="items_title">備品一覧</div>
    <%= form_with(method: :delete, url: {controller: 'items', action: 'destroy_many' }, local: true, id:"index_table_form") do |f|%>
    <table id="items-table" class="items_table">
      <tbody id="items-tbody">
        <tr id="menu-items-index" class="menu_items_index">  
          <th class="item_table"></th>
          <th class="item_table_name">名称</th>
          <th class="item_table_category">カテゴリー</th>
          <th class="item_table_quantity">在庫数</th>
          <th class="item_table_order_point">発注点</th>
          <th></th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
          
          <% @items.each do |item|%>
            <% if item.order_point >= (item.quantity + Stock.where(item_id: (item.id)).sum(:quantity) -  Ship.where(item_id: (item.id)).sum(:quantity)) %>
              <tr id="data-items-index" class="data_items_index_op">
                <td class="item_table"><%= check_box_tag "deletes[#{item.id}]", item.id %></td>
                <td class="item_table_name"><%=link_to item.name, item_path(item) %></td>
                <td class="item_table_category"><%=item.category.name%></td>
                <td class="item_table_quantity_op"><%=item.quantity + Stock.where(item_id: (item.id)).sum(:quantity) -  Ship.where(item_id: (item.id)).sum(:quantity) %> </td>
                <td class="item_table_order_point"><%=item.order_point%></td>
                <td class="item_table_button">
                  <%= link_to "詳細", item_path(item), class:"index_button" %>
                </td>
                <td class="item_table_button">
                  <%= link_to "編集", edit_item_path(item), class:"index_button" %>
                </td>
                <td class="item_table_button">
                  <%= link_to "削除", item_path(item), method: :delete, class:"index_button" %>
                </td>
                 <td class="item_table_button">
                  <%= link_to "履歴", stock_path(item), class:"index_button" %>
                </td>
              </tr>
            <% else %>
              <tr id="data-items-index" class="data_items_index">
                <td class="item_table"><%= check_box_tag "deletes[#{item.id}]", item.id %></td>
                <td class="item_table_name"><%=link_to item.name, item_path(item) %></td>
                <td class="item_table_category"><%=item.category.name%></td>
                <td class="item_table_quantity"><%=item.quantity + Stock.where(item_id: (item.id)).sum(:quantity) -  Ship.where(item_id: (item.id)).sum(:quantity) %> </td>
                <td class="item_table_order_point"><%=item.order_point%></td>
                <td class="item_table_button">
                  <%= link_to "詳細", item_path(item), class:"index_button" %>
                </td>
                <td class="item_table_button">
                  <%= link_to "編集", edit_item_path(item), class:"index_button" %>
                </td>
                <td class="item_table_button">
                  <%= link_to "削除", item_path(item), method: :delete, class:"index_button" %>
                </td>
                <td class="item_table_button">
                  <%= link_to "履歴", stock_path(item), class:"index_button" %>
                </td>
              </tr>
            <%end%>
          <%end%>
      </tbody>
    </table>
    <%= f.submit "一括削除", class:"bundle_delete_button"%>
    <%end%>
  </div>
</div>

app/views/items/new.html.erb
<div class="item_new_main">
  <%= render partial: 'layouts/pulldown'%>
  <%= render partial: 'layouts/sidebar'%>

  <div class="item_new_sub">
    <div class="item_new_sub_sub">
      <div class="item_new_subtitle">
        備品新規登録
      </div>
      <%= form_with(model: @item, local: true, class:"item_new_form_area") do |f|%>
      <div class="item_new_form">
        <div class="item_new_separate">
          <%= render 'layouts/error_messages', model: f.object %>
         
          <div class="form-example">
            <%= f.label :"備品名称", class: "form_label"  %><span class="mandatory">（必須）</span><br />
            <%= f.text_field :name, placeholder: "例：ハサミ", class:"form_text"%>
          </div>
          <div class="form-example">
            <%= f.label :"カテゴリー", class: "form_label"  %><span class="mandatory">（必須）</span><br />
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"form_text"})%>
          </div>
          <div class="form-example">
            <%= f.label :"備品数:(0でも可)", class: "form_label"  %><span class="mandatory">（必須）</span><br />
            <%= f.text_field :quantity, placeholder: "例：10（半角数字）", class:"form_text"%>
          </div>
          <div class="form-example">
            <%= f.label :"発注点", class: "form_label"  %><span class="mandatory">（必須）</span>
            <br />
            <%= f.text_field :order_point, placeholder: "例：10（半角数字）", class:"form_text"%>
          </div>
        </div>
        <div class="item_new_separate">

          <div class="form-example">
            <%= f.label :"単位", class: "form_label"  %><br />
            <%= f.text_field :unit, placeholder: "例：個、袋、etc", class:"form_text"%>
          </div>
          <div class="form-example">
            <%= f.label :"保管場所", class: "form_label"  %><br />
            <%= f.text_field :location, placeholder: "例：棚A", class:"form_text"%>
          </div>
          <div class="form-example">
            <%= f.label :"発注元", class: "form_label"  %><br />
            <%= f.text_field :store, placeholder: "例：○○社", class:"form_text"%>
          </div>
          <div class="form-example">
            <%= f.label :"備考", class: "form_label"  %><br />
            <%= f.text_area :remarks, placeholder: "例：よく切れるので注意", class:"form_text"%>
          </div>
          <div class="image_selectbox">
            <div id="file-name" class="file_name">未選択</div>
            <label for="image">
              <span class="button">画像を選択</span><%= f.file_field :image, id: "image" %>
            </label>
          </div>
        </div>
      </div>
      <div class="item_new_submit_area">
        <%= f.submit value: "登録", class: "item_new_submit"%>
      </div>
      
      <%end%>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="show_main">
  <%= render partial: 'layouts/pulldown'%>
  <%= render partial: 'layouts/sidebar'%>
  <div class="show_submain">
    <div class="show_title">
      備品詳細情報
    </div>
    <div class="show_sub">
      <div class="item_show_img">
        <%if @item.image.attached?%>
          <%= image_tag @item.image.variant(resize: '480x480'), class: 'item-image'%>
        <%else%>
          画像なし
        <%end%>
      </div>
      <div class="item_show_table_main">
        <table class="item_show_table">
          <tr class="item_shows_tr">
            <td class="item_show_menu_table">名称</td>
            <td class="item_show_data_table"><%=@item.name%></td>
          </tr>
          <tr class="item_shows_tr">
            <td class="item_show_menu_table">カテゴリー</td>
            <td class="item_show_data_table"><%=@item.category.name%></td>
          </tr>
          <tr class="item_shows_tr">
            <td class="item_show_menu_table">在庫数</td>
            <% if @quantity < @item.order_point%>
              <td class="item_show_data_table_op"><%=@quantity%></td>
            <%else%>
              <td class="item_show_data_table"><%=@quantity%></td>
            <%end%>
          </tr>
          <tr class="item_shows_tr">          
            <td class="item_show_menu_table">発注点</td>
            <td class="item_show_data_table"><%=@item.order_point%></td>
          </tr>
          <tr class="item_shows_tr">
            <td class="item_show_menu_table">保管場所</td>
            <td class="item_show_data_table"><%=@item.location%></td>
          </tr>
          <tr class="item_shows_tr">
            <td class="item_show_menu_table">発注元</td>
            <td class="item_show_data_table"><%=@item.store%></td>
          </tr>
          <tr class="item_shows_tr">
            <td class="item_show_menu_table">備考</td>
            <td class="item_show_data_table_remarks"><%=@item.remarks%></td>
          </tr>
        </table>
        <div class="show_btn">
          <div class="edit_delete_btn">
            <%=link_to "編集", edit_item_path%>
          </div>
          <div class="edit_delete_btn">
            <%=link_to "削除", item_path, method: :delete %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>