config/routes.rb
Rails.application.routes.draw do
  namespace :api, { format: 'json' } do
    namespace :v1 do # バージョン1を表している
      resources :items_api
      resources :stocks_api
      resources :ships_api
    end
  end
  devise_for :users
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
  end
  
  root to: 'stocks#index'
  resources 'items'
  resources 'stocks', only: [:new, :create, :show, :destroy]
  resources 'ships', only: [:new, :create, :index, :show, :destroy]

  delete 'items', to: 'items#destroy_many'
  post 'items/select', to: 'items#category_select'
  post 'items/quantity', to: 'items#item_quantity'
  post 'items/search', to: 'items#search_item'
  # if Rails.env.development?
  #   mount LetterOpenerWeb::Engine, at: "/letter_opener"
  # end
 
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_pulldown.html.erb
<ul class="show-lists hidden" id="pull-down" style="display: none;">
    <% if user_signed_in?%>
      <%unless current_page?(root_path)%>
        <li><%= link_to "入出庫画面", root_path, class:"sidebar_content_tb"%></li>
      <%end%>
      <%unless current_page?(new_item_path)%>
        <li><%= link_to "備品新規登録", new_item_path, class:"sidebar_content_tb"%></li>
      <%end%>
      <%unless current_page?(items_path)%>
        <li><%= link_to "登録備品一覧", items_path, class:"sidebar_content_tb"%></li>
      <%end%>
    <%end%>
  </ul>

app/views/layouts/_sidebar.html.erb
<div class="side_bar" id="side-bar">
  <% if user_signed_in?%>
    <%unless current_page?(root_path)%>
    <div class="sidebar_content">
      <%= link_to "入出庫画面", root_path, class:"sidebar_content"%>
    </div>
    <%end%>
    <%unless current_page?(new_item_path)%>
    <div class="sidebar_content">
      <%= link_to "備品新規登録", new_item_path, class:"sidebar_content"%>
    </div>
    <%end%>
    <%unless current_page?(items_path)%>
    <div class="sidebar_content">
      <%= link_to "登録備品一覧", items_path, class:"sidebar_content"%>
    </div>
    <%end%>
  <%else%>
    <div class="sign_out_sidebar_content">入出庫画面</div>
    <div class="sign_out_sidebar_content">備品新規登録</div>
    <div class="sign_out_sidebar_content">登録備品一覧</div>
  <%end%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pickup!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <script> src="/packs/application.js"</script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header_left">
         <%= link_to 'Pickup!', root_path, class:"logo" %>
         
      </div>
      <% if user_signed_in? %>
      <p id="menu" class="menu">メニュー</p>
      <%end%>
      <% unless user_signed_in? %>
      <div class="header_right login">
        管理者:  
        <% unless current_page?(new_user_session_path)%>
          <%= link_to 'ログイン', new_user_session_path, id:"sign-in-flag", class:"header_right_login" %>
        <%end%>
        <%unless current_page?(new_user_registration_path)%>
          <%= link_to '新規登録', new_user_registration_path, class:"header_right_login" %>
        <%end%>
      </div>
      <% else %>
      <div class="header_right logout">
        管理者:  <%= current_user.name %> <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"header_right_login" %>
      </div>
      <%end%>
    </header>
    <%= yield %>
    <footer>
      <div class="footer_center">
        ©️2022 Pickup
      </div>
    </footer>
  </body>
</html>